language: node_js
node_js:
  - "8.10.0"
  # safelist
branches:
  only:
  - master
  - develop

install:
  - npm install

services:
  - postgresql

  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

cache:
  directories:
  - node_modules
after_success:
- npm run coveralls