language: node_js
node_js:
  - "8.10.0"
  # safelist
branches:
  only:
  - master
  - develop

install:
  - npm install

script:
  - npm test

cache:
  directories:
  - node_modules
after_success:
- npm run coveralls