language: node_js
node_js:
  - "8.10.0"
  # safelist

install:
  - npm install

before_script:
  - psql -c "create database stackoverflowdb;" -U postgres
  - psql -c "create user root with password 'password';" -U postgres

script:
  - npm test

# cache:
#   directories:
#   - node_modules
after_success:
- npm run coveralls